#ifndef ZEN_BINDLESS_H
#define ZEN_BINDLESS_H

#define ZEN_BINDLESS_HEAP_SET 0

#define ZEN_BINDLESS_HEAP_BINDING_TEXTURE2D   0
#define ZEN_BINDLESS_HEAP_BINDING_TEXTURECUBE 1
#define ZEN_BINDLESS_HEAP_BINDING_SAMPLER     2


#endif // ZEN_BINDLESS_H
