git submodule add https://github.com/gabime/spdlog External/spdlog
git submodule add https://github.com/glfw/glfw External/glfw
git submodule add https://github.com/g-truc/glm External/glm
git submodule add https://github.com/KhronosGroup/SPIRV-Cross External/spirv-cross
git submodule add https://github.com/GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator External/vma
git submodule add https://github.com/zeux/volk External/volk
git submodule add https://github.com/google/googletest External/googletest
git submodule add https://github.com/tcbrindle/span External/span
git submodule add https://github.com/nothings/stb External/stb
git submodule add https://github.com/syoyo/tinygltf External/tinygltf
git submodule add https://github.com/g-truc/gli External/gli
git submodule add https://github.com/spnda/fastgltf.git External/fastgltf