#version 450
#extension GL_GOOGLE_include_directive : require
#include "../cone_trace.glsl"

layout(local_size_x=64) in;
layout(set=1,binding=0,std430) readonly buffer EnvironmentNormals { vec4 normals[]; };
layout(set=1,binding=1,std430) writeonly buffer EnvironmentResults { vec4 results[]; };

void main()
{
    uint index = gl_GlobalInvocationID.x;
    if (index < normals.length())
    {
        vec3 normal = normals[index].xyz;
        results[index] = vec4(DiffuseVoxelLighting(vec3(2.0), normal),
            VoxelEnvironmentConeVisibility(voxelOpacity, TraceOrigin(vec3(2.0), normal), normal));
    }
}
