#version 460
#extension GL_EXT_ray_query : require
layout(local_size_x=1) in;
layout(set=1,binding=0) uniform accelerationStructureEXT testScene;
layout(std430,set=1,binding=1) writeonly buffer Results { vec4 values[]; };
void main()
{
    uint index=gl_GlobalInvocationID.x;
    rayQueryEXT query;
    float x=index==2u ? 2.0 : index==3u ? 4.0 : 0.0;
    rayQueryInitializeEXT(query,testScene,0u,0xffu,vec3(x,0,-1),0.0,vec3(0,0,1),10.0);
    while(rayQueryProceedEXT(query))
    {
        if(rayQueryGetIntersectionTypeEXT(query,false)==gl_RayQueryCandidateIntersectionTriangleEXT)
        {
            if(index!=1u || rayQueryGetIntersectionPrimitiveIndexEXT(query,false)!=0u)
                rayQueryConfirmIntersectionEXT(query);
        }
    }
    vec4 value=vec4(-1);
    if(rayQueryGetIntersectionTypeEXT(query,true)==gl_RayQueryCommittedIntersectionTriangleEXT)
    {
        value=vec4(rayQueryGetIntersectionTEXT(query,true),rayQueryGetIntersectionBarycentricsEXT(query,true),
                   float(rayQueryGetIntersectionInstanceCustomIndexEXT(query,true)));
    }
    values[index]=value;
}
