#version 460
#extension GL_GOOGLE_include_directive : require
#extension GL_EXT_ray_query : require
#define HYBRID_HARDWARE_PROVIDER 1
#include "../hybrid_provider.glsl"
layout(local_size_x=1) in;
layout(std430,set=1,binding=0) writeonly buffer Results { vec4 values[]; };
layout(push_constant) uniform QueryConstants { vec4 worldOffset; } query;
void main()
{
    uint index=gl_GlobalInvocationID.x;
    vec3 origin=vec3(float(index)*2.0,0,-1)+query.worldOffset.xyz;
    HardwareRayHit hit=HardwareQuery(origin,vec3(0,0,1),100.0,true);
    values[index]=vec4(hit.ray.hit ? hit.ray.position.z-origin.z : -1.0,
        float(hit.material),float(hit.instance),float(hit.generation.x));
}
