#version 450
#extension GL_GOOGLE_include_directive : require
#include "frame_common.glsl"
layout(local_size_x=GI_QUERY_GROUP_SIZE) in;
layout(set=3,binding=1,std430) writeonly buffer StaticFlags { uint staticFlags[]; };
layout(set=3,binding=2,std430) writeonly buffer DynamicFlags { uint dynamicFlags[]; };
layout(set=3,binding=3,std430) writeonly buffer StaticReceivers { uint staticReceivers[]; };
layout(set=3,binding=4,std430) writeonly buffer DynamicReceivers { uint dynamicReceivers[]; };
void main() {
    uint cell=StaticItem(),n=staticGI.volume.x;
    if(cell<n*n*n) {
        staticFlags[cell]=0u; dynamicFlags[cell]=0u;
        staticReceivers[cell]=GI_INVALID_CELL; dynamicReceivers[cell]=GI_INVALID_CELL;
    }
}
