#version 450
#extension GL_GOOGLE_include_directive : require

#include "../Common/bindless_heap.glsl"

layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

struct VkDispatchIndirectCommand
{
    uint x;
    uint y;
    uint z;
};

layout(std140, set = 1, binding = 0) writeonly buffer IndirectBuffer
{
    VkDispatchIndirectCommand command;
};

void main()
{
    command.x = 0;
    ;
}
