#version 450
#extension GL_GOOGLE_include_directive : require

#include "../Common/bindless_heap.glsl"

layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

struct DrawIndexedIndirectCommand
{
    uint indexCount;
    uint instanceCount;
    uint firstIndex;
    int vertexOffset;
    uint firstInstance;
};

layout(std430, set = 1, binding = 0) writeonly buffer IndirectBuffer
{
    DrawIndexedIndirectCommand command;
};

void main()
{
    command.instanceCount = 0;
}
