#version 450
#extension GL_GOOGLE_include_directive : require
#include "../Common/bindless_heap.glsl"
#include "gi_common.glsl"
#include "Graphics/Shared/VoxelGI.h"
layout(local_size_x=ZEN_VOXEL_VOLUME_GROUP_SIZE, local_size_x_id=ZEN_VOXEL_VOLUME_GROUP_X_ID,
       local_size_y=ZEN_VOXEL_VOLUME_GROUP_SIZE, local_size_y_id=ZEN_VOXEL_VOLUME_GROUP_Y_ID,
       local_size_z=ZEN_VOXEL_VOLUME_GROUP_SIZE, local_size_z_id=ZEN_VOXEL_VOLUME_GROUP_Z_ID) in;
layout(set=1,binding=0) uniform sampler3D voxelAlbedo;
layout(set=1,binding=1) uniform sampler3D voxelNormal;
layout(set=1,binding=2) uniform samplerCube skyboxMap;
layout(set=1,binding=3,rgba16f) uniform writeonly image3D skyIrradiance;
void main()
{
    ivec3 p=ivec3(gl_GlobalInvocationID);
    if(any(greaterThanEqual(p,imageSize(skyIrradiance)))) return;
    vec3 irradiance=vec3(0);
    if(texelFetch(voxelAlbedo,p,0).a>0.5 && sceneUbo.environment.z>0)
    {
        vec3 normal=normalize(texelFetch(voxelNormal,p,0).rgb*2.0-1.0);
        vec3 position=gi.gridMinVoxelSize.xyz+(vec3(p)+0.5)*gi.gridMinVoxelSize.w;
        vec3 origin=TraceOrigin(position,normal);
        int count=int(gi.limits.x);
        for(int i=0;i<count;++i)
        {
            float weight;
            vec3 direction=HemisphereCone(normal,i,count,weight);
            float visibility=VoxelVisibility(voxelAlbedo,origin,direction,1e20);
            irradiance+=textureLod(skyboxMap,EnvironmentSourceDirection(direction),0).rgb*visibility*weight;
        }
        irradiance*=3.14159265359*sceneUbo.environment.x;
    }
    imageStore(skyIrradiance,p,vec4(irradiance,0));
}
