#version 450
layout(local_size_x = 1) in;
layout(set = 0, binding = 0, std430) buffer Data { uint value; } data;
layout(set = 0, binding = 1, r32ui) uniform uimage2D image;
layout(set = 0, binding = 2, std430) writeonly buffer Output { uint values[2]; } result;
layout(push_constant) uniform Parameters { uint initialize; } params;

void main()
{
    uint bufferValue = params.initialize != 0 ? 11 : data.value + 5;
    uint imageValue = params.initialize != 0 ? 13 : imageLoad(image, ivec2(0)).x + 7;
    data.value = bufferValue;
    imageStore(image, ivec2(0), uvec4(imageValue, 0, 0, 0));
    result.values[0] = bufferValue;
    result.values[1] = imageValue;
}
