#version 450
#extension GL_EXT_nonuniform_qualifier : require
layout(local_size_x = 1) in;
layout(set = 0, binding = 0) uniform texture2D textures[];
layout(set = 0, binding = 2) uniform sampler samplers[];
layout(set = 2, binding = 0, std430) buffer Result { uint color; } result;
layout(push_constant) uniform Constants { uint index; } constants;
void main()
{
    result.color = packUnorm4x8(texture(sampler2D(textures[nonuniformEXT(constants.index)],
        samplers[nonuniformEXT(constants.index)]), vec2(0.5)));
}
