#version 450
layout(local_size_x = 1) in;
layout(set = 0, binding = 0) uniform usamplerBuffer inputBuffer;
layout(set = 0, binding = 1, r32ui) uniform writeonly uimageBuffer outputBuffer;
void main()
{
    int inputCount = textureSize(inputBuffer);
    imageStore(outputBuffer, 0, texelFetch(inputBuffer, inputCount - 1) + uvec4(100));
    imageStore(outputBuffer, 1, uvec4(inputCount + 10 * imageSize(outputBuffer)));
}
